# YouTube Shorts Automation System Configuration

workflow:
  default_interval_minutes: 60  # How often to generate videos (in minutes)
  max_videos_per_day: 10  # Maximum number of videos to generate per day
  auto_start: false  # Whether to automatically start workflow on application launch

content:
  spreadsheet_id: ""  # Google Sheets ID for content database
  google_sheets_credentials_file: "config/google_credentials.json"  # Path to Google API credentials
  output_spreadsheet_id: ""  # Google Sheets ID for tracking uploads
  watermark_text: "Generated Video"  # Watermark text to add to videos
  brand_text: "YouTube Shorts Automation"  # Branding text for intro/outro
  default_themes:
    - "travel"
    - "tech"
    - "cooking"
    - "fitness"
    - "science"
    - "nature"
    - "education"
    - "humor"

video:
  resolution: "1080x1920"  # Vertical for shorts
  duration_seconds: 60  # Total video duration in seconds
  fps: 30  # Frames per second
  bitrate: "8000k"  # Video bitrate
  style: "standard"  # Video style (standard, ken_burns)
  add_watermark: true  # Whether to add watermark
  transitions: true  # Whether to add transitions between images
  add_intro: true  # Whether to add intro slides
  add_outro: true  # Whether to add outro slides

image:
  count_per_video: 5  # Number of images per video
  style: "photorealistic"  # Image style (photorealistic, anime, artistic, cinematic, minimalist)
  negative_prompt: "low quality, blurry, distorted, deformed, disfigured, ugly, bad anatomy"  # Things to avoid in images

audio:
  duration_seconds: 60  # Audio duration in seconds
  fade_in_seconds: 1  # Fade in duration in seconds
  fade_out_seconds: 2  # Fade out duration in seconds
  use_tts: false  # Whether to use text-to-speech
  tts_voice: "en-US-Standard-D"  # Voice ID for TTS
  provider: "tts"  # Audio provider (tts, music)
  background_volume: -15  # Background volume adjustment in dB

youtube:
  default_category_id: "22"  # 22 is "People & Blogs"
  default_privacy: "private"  # Initial privacy setting (private, unlisted, public)
  auto_publish: false  # Whether to automatically publish videos
  publish_delay_hours: 24  # Delay before publishing in hours
  max_size_mb: 100  # Maximum video size in MB
  credentials_file: "config/youtube_credentials.json"  # Path to YouTube API credentials

gui:
  theme: "system"  # GUI theme (light, dark, system)
  auto_save_logs: true  # Whether to automatically save logs
  refresh_interval_seconds: 1  # UI refresh interval in seconds